apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/paddlesurf-140814/app
        ports:
        - containerPort: 4567
        env:
        - name: REDIS_HOST
          value: redis

